spring.profiles.active=prod

spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/changelog-master.yaml

spring.web.error.include-stacktrace=never
spring.web.error.include-message=never

jwt.secret=my-very-long-secret-key-for-appliance-store-assessment-which-is-secure
jwt.expiration=813421000
